export const fontFamily = {
    GothamBlack: 'Gotham-Black',
    GothamBlackItalic: 'Gotham-BlackItalic',
    GothamBold: 'Gotham-Bold',
    GothamBoldItalic: 'Gotham-BoldItalic',
    GothamExtraBold: 'Gotham-ExtraBold',
    GothamExtraBoldItalic: 'Gotham-ExtraBoldItalic',
    GothamExtraLight: 'Gotham-ExtraLight',
    GothamExtraLightItalic: 'Gotham-ExtraLightItalic',
    GothamItalic: 'Gotham-Italic',
    GothamLight: 'Gotham-Light',
    GothamLightItalic: 'Gotham-LightItalic',
    GothamMedium: 'Gotham-Medium',
    GothamMediumItalic: 'Gotham-MediumItalic',
    GothamRegular: 'Gotham-Regular',
    GothamSemiBold: 'Gotham-SemiBold',
    GothamSemiBoldItalic: 'Gotham-SemiBoldItalic',
    GothamThin: 'Gotham-Thin',
    GothamThinItalic: 'Gotham-ThinItalic',
  };